GET http://localhost:5111/villain/batman HTTP/1.1

###
POST http://localhost:5111/villain HTTP/1.1
content-type: application/json

{
    "name": "Joker",
    "hero": "Batman",
    "description": "Si bien sus orígenes y rasgos han variado con el transcurso del tiempo, por lo general se le asocia con una personalidad psicópata con un humor sádico y retorcido, lo que le ha llevado a ser catalogado como la antítesis de Batman."
}

###
GET http://localhost:3501/v1.0/invoke/tour-of-villains-api/method/villain/batman HTTP/1.1

###
POST http://localhost:3501/v1.0/invoke/tour-of-villains-api/method/villain HTTP/1.1
content-type: application/json

{
    "name": "Octopus",
    "hero": "Spiderman",
    "description": "Es un científico loco muy inteligente y algo fornido que tiene cuatro apéndices fuertes que se asemejan a los tentáculos de un pulpo, que se extienden desde la parte posterior de su cuerpo y pueden usarse para varios propósitos."
}

###
GET http://localhost:3501/v1.0/invoke/tour-of-villains-api/method/villain/spiderman HTTP/1.1