GET http://localhost:5111/villain/batman HTTP/1.1

###
POST http://localhost:5111/villain HTTP/1.1
content-type: application/json

{
    "Name": "Joker",
    "hero":{
        "name": "Batman",
        "description": "Un multimillonario magnate empresarial y filántropo dueño de Empresas Wayne en Gotham City. Después de presenciar el asesinato de sus padres, el Dr. Thomas Wayne y Martha Wayne en un violento y fallido asalto cuando era niño, juró venganza contra los criminales, un juramento moderado por el sentido de la justicia.",
        "alterEgo": "Bruce Wayne"     
    },
    "description": "Si bien sus orígenes y rasgos han variado con el transcurso del tiempo, por lo general se le asocia con una personalidad psicópata con un humor sádico y retorcido, lo que le ha llevado a ser catalogado como la antítesis de Batman."
}

###
GET http://localhost:3501/v1.0/invoke/tour-of-villains-api/method/villain/batman HTTP/1.1

###
POST http://localhost:3501/v1.0/invoke/tour-of-villains-api/method/villain HTTP/1.1
content-type: application/json

{
    "name": "Octopus",
    "hero":{
        "name": "Spiderman",
        "description": "un joven huérfano neoyorquino que adquiere superpoderes después de ser mordido por una araña radiactiva, y cuya ideología como héroe se ve reflejada primordialmente en la expresión «un gran poder conlleva una gran responsabilidad».20​21​ Suele ser asociado con una personalidad bromista, amable, inventiva y optimista, lo que le ha llevado a ser catalogado como el «vecino amigable» de cualquiera lo cual, aunado a sus vivencias caracterizadas por los problemas cotidianos.",
        "alterEgo": "Peter Parker"     
    },
    "description": "Es un científico loco muy inteligente y algo fornido que tiene cuatro apéndices fuertes que se asemejan a los tentáculos de un pulpo, que se extienden desde la parte posterior de su cuerpo y pueden usarse para varios propósitos."
}

###
GET http://localhost:3501/v1.0/invoke/tour-of-villains-api/method/villain/spiderman HTTP/1.1