GET http://localhost:5111/villain/batman HTTP/1.1

###
POST http://localhost:5111/villain HTTP/1.1
content-type: application/json

{
    "Name": "Joker",
    "hero":{
        "name": "Batman",
        "description": "Un multimillonario magnate empresarial y filántropo dueño de Empresas Wayne en Gotham City. Después de presenciar el asesinato de sus padres, el Dr. Thomas Wayne y Martha Wayne en un violento y fallido asalto cuando era niño, juró venganza contra los criminales, un juramento moderado por el sentido de la justicia.",
        "alterEgo": "Bruce Wayne"     
    },
    "description": "Si bien sus orígenes y rasgos han variado con el transcurso del tiempo, por lo general se le asocia con una personalidad psicópata con un humor sádico y retorcido, lo que le ha llevado a ser catalogado como la antítesis de Batman."
}

###
GET  http://localhost:5111/villain/batman HTTP/1.1

###
POST  http://localhost:5111/villain HTTP/1.1
content-type: application/json

{
    "name": "Octopus",
    "hero":{
        "name": "Spiderman",
        "description": "un joven huérfano neoyorquino que adquiere superpoderes después de ser mordido por una araña radiactiva, y cuya ideología como héroe se ve reflejada primordialmente en la expresión «un gran poder conlleva una gran responsabilidad».20​21​ Suele ser asociado con una personalidad bromista, amable, inventiva y optimista, lo que le ha llevado a ser catalogado como el «vecino amigable» de cualquiera lo cual, aunado a sus vivencias caracterizadas por los problemas cotidianos.",
        "alterEgo": "Peter Parker"     
    },
    "description": "Es un científico loco muy inteligente y algo fornido que tiene cuatro apéndices fuertes que se asemejan a los tentáculos de un pulpo, que se extienden desde la parte posterior de su cuerpo y pueden usarse para varios propósitos."
}

###
POST  http://localhost:5111/villain HTTP/1.1
content-type: application/json

{
    "name": "Doctor Muerte",
    "hero":{
        "name": "Luke Cage",
        "description": "Es un exconvicto encarcelado por un crimen que no cometió, que gana los poderes de la fuerza sobrehumana y la piel irrompible después de someterse voluntariamente a un procedimiento experimental.",
        "alterEgo": "Carl Lucas"     
    },
    "description": "No solo cuenta con una armadura personal que rivaliza con las de Iron Man, albergando un variopinto y nutrido arsenal, sino que además es un hechicero de primera, estando mano a mano con el propio Doctor Extraño."
}

###
POST  http://localhost:5111/villain HTTP/1.1
content-type: application/json

{
    "name": "Loki",
    "hero":{
        "name": "Thor",
        "description": "Es el dios del trueno y fuerza en la mitología nórdica y germánica. Su papel es complejo ya que tenía influencia en áreas muy diferentes, tales como el clima, las cosechas, la protección, la consagración, la justicia, las lidias, los viajes y las batallas.",
        "alterEgo": "Thor"     
    },
    "description": "El dios nórdico de las Mentiras y el Engaño. Y el hermano adoptivo de Thor según la mitología de Marvel y también su mayor rival clásico."
}


###
GET  http://localhost:5111/villain/thor HTTP/1.1

